name: Prod

on:
  push:
    branches:
      - master
      - patch-release
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Build Results
        # Prevent error on re-run
        # https://github.com/actions/cache/issues/107#issuecomment-556037278
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        id: build-cache
        uses: actions/cache@v1
        with:
          path: .cache
          key: v1-build-cache-${{ hashFiles('yarn.lock') }}-${{ github.ref }}-
          restore-keys: |
            v1-build-cache-${{ hashFiles('yarn.lock') }}-${{ github.ref }}-
            v1-build-cache-${{ hashFiles('yarn.lock') }}-refs/heads/${{ github.base_ref }}-
            v1-build-cache-${{ hashFiles('yarn.lock') }}-refs/heads/master-

      # Unknown reason `scripts/build/build.js` created dir can't work
      - run: mkdir -p .cache/files

      - name: Build Package
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist

      - name: Lint Code
        run: yarn lint:dist

  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        node:
          - "13"
          - "12"
          - "10"
        exclude:
          - os: "macos-latest"
            node: "13"
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: dist

      - name: Run Tests (macOS)
        if: matrix.os == 'macos-latest'
        run: yarn test:dist --maxWorkers=4

      - name: Run Tests (Linux and Windows)
        if: matrix.os != 'macos-latest'
        run: yarn test:dist --maxWorkers=2

      - name: Run Tests (standalone) (macOS)
        if: matrix.os == 'macos-latest'
        run: yarn test:dist-standalone --maxWorkers=4

      - name: Run Tests (standalone) (Linux and Windows)
        if: matrix.os != 'macos-latest'
        run: yarn test:dist-standalone --maxWorkers=2
